travis:
  secure:
    BINSTAR_TOKEN: kzpUIrM/7AlJcXGYG0myJjve4TeEaOlauo0VyDwEzPaOfY3/TUGGE6FfEeclPLwI8j0eFWTuWXH1xdThy4FUmXuiIv1vj/IXnE6P7niUU+gOFYq/+z93OyYbKcVyU/AMaX5peFBvQQCdFjmzDUusuX/xkOZaLgiFsiAaDAOUrjd6ONPQ/7uJRd3qOr3lbSSaWrBbOHoDm95puUMg1M1xoMCl4XMsOe9y13GBImFypqjicWGSkYLtLLHLEAKKOtqtnkqfnvd3+5HVkwavTntaCYxJfdbuifSV8foW+z1Mn+Zt5ve8PLqXz20hzLOQAMUNTu3IGaoHIGvaiZFpzga+eE0HSkLRSqyTx2IYSpnQnmKk0AMU19B93CTh4H9nx3gV6zSGI2jmCGr8OlKglK1Epkcxc1/0mGXtixU9kdwwyFkasoEF7R9LpBpG2/x9npB3cbL/ELun4cu9vaFG52ZzlDF/qyZaM77vQZ6W+2gPck+WFBK06hoxwtWn1OU9LqKOMOWwBOH+i6YupVFSp7tZhH/8iS0s2uChEyEFDTYWQVhjLz9+pvVcFhq1qmxux8sf8azVTibbsejOPl5YBWzS21/X0uMo7Nv+xvYAmlang6pihCKEimJfA66o6U+mQy2yktMsnrh5Mu4wFm+yyLc5LEiKCCjXBJMf5uMQxh0slbc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
